from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.method),
    path('login', views.login),
    path('userlogin', views.userlogin),
    path('signup', views.signup),
    path('newuserRegistration', views.newuserRegistration),
    path('logout', views.logout),
    path('admin', views.writePassword),
    path('confirmAdminPassword', views.confirmAdminPassword),
    path('adminDashboard', views.ShowadminDashboard),
    path('showallUsers', views.showallUsers),
    path('showallEmployees', views.showallEmployees),
    path('admin/menu', views.addMenu),
    path('addemployee', views.addemployee),
    path('deleteEmployee/<int:id>', views.deleteEmployee),
    path('editEmployee/<int:id>', views.editEmployee),
    path('edit/<int:id>', views.updateEmployeee),
    path('showEmployee/<int:id>', views.showEmployee),
    path('bookTable', views.bookTable),
    path('ordernow', views.ordernow),
    path('error', views.error),
    path('sendmessage/<int:id>', views.sendmessage),
    path('deletemessage/<int:id>', views.deletemessage),
    path('ordernow/<int:id>', views.addToCart),
    path('ordernow/success', views.completeOrder),
    path('showallOrders', views.showallOrders),
    path('processTrue/<int:id>', views.processTrue),
    path('destroyOrder/<int:id>', views.destroyOrder),
    path('Showmessage/<int:id>', views.ShowmessageReservation),
    path('toEditMenu', views.toEditMenu),
    path('EditAtMenu/<int:id>', views.EditAtMenu),
    path('deleteFromMenu/<int:id>', views.deleteFromMenu),
    path('AcceptEvent/<int:id>', views.AcceptEvent),
    path('RefucedEvent/<int:id>', views.RefucedEvent),
    path('deleteEvent/<int:id>', views.deleteEvent),
    path('EditEstimatedCost/<int:id>', views.EditEstimatedCost),
    path('showReports', views.showReports),
    path('report/pickCustomer', views.pickRandom),
    path('ManageAccount/<int:id>', views.ManageAccount),
    path('EditUserProfile/<int:id>', views.EditUserProfile),
    path('deleteEmployee/<int:id>', views.deleteEmployee),
    path('viewPreEmployee', views.pre),
    path('restoreEmployee/<int:id>', views.restore),
    
    
]