# Generated by Django 4.1.2 on 2022-10-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_app', '0004_meal_image_alter_cart_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered', to='vintage_app.meal'),
        ),
    ]
