# Generated by Django 4.1.2 on 2022-10-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_app', '0005_alter_cart_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='vintage_app.meal'),
            preserve_default=False,
        ),
    ]
