# Generated by Django 4.1.2 on 2022-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_app', '0006_alter_cart_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
