# Generated by Django 4.1.2 on 2022-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_app', '0007_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='notyet', max_length=255),
        ),
    ]
