# Generated by Django 4.1.1 on 2022-10-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_app', '0009_alter_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
