# Generated by Django 4.1.1 on 2022-10-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_app', '0010_customer_count1_meal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_situation',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered', to='vintage_app.meal'),
        ),
    ]
